name: Build WiX Web site

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        manual: true

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOCUSAURUS_SSR_CONCURRENCY: 5

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Npm restore
        shell: cmd
        run: ./src/restore.cmd

      - name: Build wixweb
        shell: cmd
        run: ./src/build.cmd release

      # Do NOT publish logs on `master` branch as they may contain secrets in them.
      - name: Save logs
        if: github.ref != 'refs/heads/master' && (success() || failure())
        uses: actions/upload-artifact@v3
        with:
          name: logs_${{ github.run_id }}
          path: build/logs/

      - name: Deploy
        if: github.ref == 'refs/heads/master' && success()
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          app-name: wixtoolset
          package: ./build/deploy
